version: '2'
services:
  web:
    build: .
    container_name: server
    volumes:
        - .:/code
    command: python manage.py runserver -h 0.0.0.0 -p 8080
    ports:
        - "8080:8080"

    networks:
        - default


networks:
  default:
      external:
        name: redash_default